### ISSUE TITLE
A question about evaluation metrics

### ISSUE THREAD

**Issue by LucasWang16** [WOW5678/CompNet#1]
Hello,
I want to reference your paper in my work. But I am confused about the evaluation metircs in your paper. They look similar with metrics used in GAMENet paper, but the values are in big difference.
What is the difference between yours and theirs among these metrics? Can I just use the results in this paper for comparison in future work?

**Comment by gaifengru** [comment]
Hello, I would like to inquire if you have successfully run the CompNet code and how long it will take to run. I have encountered some difficulties recently and would like to ask for your advice
